### ISSUE TITLE
LeptonEfficiencyCorrector Can't run over Condor

### ISSUE THREAD

**Issue by zhenbinwu** [susy2015/NanoSUSY-tools#16]
It seems there are dependency on local environment with the LeptonEfficiencyCorrector on Condor as below. Maybe we need to shift the shared object. Compiling is also not supported by LPC: https://uscms.org/uscms_at_work/computing/setup/batch_systems_advanced.shtml#Compilation

```
 91 echo $EXE $argv[2-]
 92 python $EXE $argv[2-]
 93 cling::DynamicLibraryManager::loadLibrary(): /uscms/home/benwu/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: cannot open      shared object file: No such file or directory
 94 Traceback (most recent call last):
 95   File "Stop0l_postproc.py", line 111, in <module>
 96     main(args)
 97   File "Stop0l_postproc.py", line 83, in main
 98     p.run()
 99   File "/storage/local/data1/condor/execute/dir_25752/CMSSW_10_2_9/python/PhysicsTools/NanoAODTools/postprocessing/framework/                postprocessor.py", line 75, in run
100     m.beginJob()
101   File "/storage/local/data1/condor/execute/dir_25752/CMSSW_10_2_9/python/PhysicsTools/NanoSUSYTools/modules/lepSFProducer.py", line 67,     in beginJob
102     self._worker_mu = ROOT.LeptonEfficiencyCorrector(self.mu_f,self.mu_h)
103   File "/cvmfs/cms.cern.ch/slc6_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/ROOT.py", line 470, in __getattr2
104     raise AttributeError( name )
105 AttributeError: LeptonEfficiencyCorrector
```

**Comment by pastika** [comment]
I assume this is resolved given that we made NTuples with this module running?

**Comment by zhenbinwu** [comment]
oh, that was fixed right after I posted this issue.
