### ISSUE TITLE
Trying to run latest Stop0l_postproc.py

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/NanoSUSY-tools#57]
Before updating to the newest top tagger tag I had this error:
```
cmslpc35.fnal.gov processors # (dev_v3) python Stop0l_postproc.py -i file:root://cmseos.fnal.gov//eos/uscms/store/user/lpcsusyhad/Stop_production/Summer16_94X_v3/PreProcessed_22Feb2019/GJets_DR-0p4_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/2016_MINIAODv3_RunIISummer16MiniAODv3-PUMoriond17_qcut19_94X_v3-v2/190225_155158/0000/prod2016MC_NANO_1-1.root -s GJets_HT_600ToInf_2016 -e 2016 -m 500
Traceback (most recent call last):
  File "Stop0l_postproc.py", line 321, in <module>
    main(args)
  File "Stop0l_postproc.py", line 215, in main
    systToSave=["Btag_Up", "Btag_Down", "Pileup_Up", "Pileup_Down", "CSPur_Up", "CSPur_Down", "Stat_Up", "Stat_Down", "Closure_Up", "Closure_Down"]),
TypeError: __init__() got an unexpected keyword argument 'saveSFAndSyst'
```
I assume that an argument was added to TopTaggerProducer.

Now I have checked out the newer tag “Stop0l_NanoAOD_production_V3.0” of the top tagger.
I now have a different error instead.
```
cmslpc35.fnal.gov processors # (dev_v3) python Stop0l_postproc.py -i file:root://cmseos.fnal.gov//eos/uscms/store/user/lpcsusyhad/Stop_production/Summer16_94X_v3/PreProcessed_22Feb2019/GJets_DR-0p4_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/2016_MINIAODv3_RunIISummer16MiniAODv3-PUMoriond17_qcut19_94X_v3-v2/190225_155158/0000/prod2016MC_NANO_1-1.root -s GJets_HT_600ToInf_2016 -e 2016 -m 500
2019-08-18 17:36:30.127838: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
Error in <TFile::TFile>: file TopTagSF_AltTWP.root does not exist
TopTagger exception message: /uscms_data/d3/caleb/SusyAnalysis/NanoSUSY/CMSSW_10_2_9/src/TopTagger/TopTagger/test/../..//TopTagger/src/TTMScaleSyst.cpp:43, in function "getParameters" -- File "TopTagSF_AltTWP.root" is not valid
Traceback (most recent call last):
  File "Stop0l_postproc.py", line 321, in <module>
    main(args)
  File "Stop0l_postproc.py", line 215, in main
    systToSave=["Btag_Up", "Btag_Down", "Pileup_Up", "Pileup_Down", "CSPur_Up", "CSPur_Down", "Stat_Up", "Stat_Down", "Closure_Up", "Closure_Down"]),
  File "/uscms_data/d3/caleb/SusyAnalysis/NanoSUSY/CMSSW_10_2_9/python/TopTagger/TopTagger/TopTaggerProducer.py", line 32, in __init__
    self.tt = TopTagger(self.topTaggerCfg, self.topTaggerWD)
  File "/uscms_data/d3/caleb/SusyAnalysis/NanoSUSY/CMSSW_10_2_9/python/TopTagger/TopTagger/TopTagger.py", line 98, in __init__
    self.initialize()
  File "/uscms_data/d3/caleb/SusyAnalysis/NanoSUSY/CMSSW_10_2_9/python/TopTagger/TopTagger/TopTagger.py", line 113, in initialize
    self.tt = tti.setup(self.cfgFile, self.workingDir)
RuntimeError: TopTagger exception thrown. TTException message: /uscms_data/d3/caleb/SusyAnalysis/NanoSUSY/CMSSW_10_2_9/src/TopTagger/TopTagger/test/../..//TopTagger/src/TTMScaleSyst.cpp:43, in function "getParameters" -- File "TopTagSF_AltTWP.root" is not valid
```
I tried removing my old top tagger config file.
```
TopTagger.cfg -> /uscms_data/d3/caleb/SusyAnalysis/NanoSUSY/CMSSW_10_2_9/src/PhysicsTools/NanoSUSYTools/python/processors/TopTaggerCfg-DeepResolved_DeepCSV_GR_nanoAOD_V1.0.0/TopTagger.cfg
```
Removing TopTagger.cfg did not fix this second error.

**Comment by caleb-james-smith** [comment]
I am following the updated readme to get the latest top tagger version. 

https://github.com/susy2015/NanoSUSY-tools/tree/dev_v3#set-up-nanosusytools-framework

**Comment by zhenbinwu** [comment]
Why do you need to run v3 now?

**Comment by pastika** [comment]
Fixed in #60

**Comment by caleb-james-smith** [comment]
Thanks, I will try again using your fixes @pastika .

**Comment by caleb-james-smith** [comment]
Ok, after testing using the latest top tagger and top tagger config versions from the readme, the errors are gone.

https://github.com/susy2015/NanoSUSY-tools/tree/dev_v3#set-up-nanosusytools-framework

**Comment by caleb-james-smith** [comment]
Hi @zhenbinwu I was running v3 to test my PR: https://github.com/susy2015/NanoSUSY-tools/pull/59

**Comment by caleb-james-smith** [comment]
I will close the issue.
